config/routes.rb
SongRank::Application.routes.draw do
  resources :directories

  resources :albums
  resources :ratings, only: :update

  root to: "albums#index"
end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :artist
  has_many :tracks

  validates_presence_of :artist
  validates_presence_of :name
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :albums

  validates_presence_of :name
end

app/models/directory.rb
class Directory < ActiveRecord::Base
  attr_reader :name
  after_save :create_symbolic_link

  def name
    folder_name = self.full_path.split('/')[-1]
    [ Rails.root, 'public', folder_name ].join('/')
  end 

  def files
    results = []
    Filetype.allowed_types.each do |t|
      results << Dir.glob([Directory.last.name, "**/*.#{t}"].join('/'))
    end
    results.flatten
  end

  protected
  def create_symbolic_link
    system("ln -nfs #{self.full_path} #{self.name}")
  end
end

app/models/filetype.rb
class Filetype < ActiveRecord::Base
  def self.allowed_types
    all.map { |f| f.name }
  end
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :track

  validates_numericality_of :score, only_integer: true
  validates_inclusion_of :score, in: 0..5
end

app/models/track.rb
class Track < ActiveRecord::Base
  belongs_to :album
  has_many :ratings

  validates_presence_of :name
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  def index
    @albums = Album.all
  end

  def show
    @ratings = []
    @album.tracks.each do |t|
      @ratings << Rating.find_or_create_by(track_id: t.id)
    end
  end

  def new
    @album = Album.new
  end

  def edit
  end

  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :release_date, :artist_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/directories_controller.rb
class DirectoriesController < ApplicationController
  before_action :set_directory, only: [:show, :edit, :update, :destroy]

  # GET /directories
  # GET /directories.json
  def index
    @directories = Directory.all
  end

  # GET /directories/1
  # GET /directories/1.json
  def show
  end

  # GET /directories/new
  def new
    @directory = Directory.new
  end

  # GET /directories/1/edit
  def edit
  end

  # POST /directories
  # POST /directories.json
  def create
    @directory = Directory.new(directory_params)

    respond_to do |format|
      if @directory.save
        format.html { redirect_to @directory, notice: 'Directory was successfully created.' }
        format.json { render action: 'show', status: :created, location: @directory }
      else
        format.html { render action: 'new' }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directories/1
  # PATCH/PUT /directories/1.json
  def update
    respond_to do |format|
      if @directory.update(directory_params)
        format.html { redirect_to @directory, notice: 'Directory was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @directory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directories/1
  # DELETE /directories/1.json
  def destroy
    @directory.destroy
    respond_to do |format|
      format.html { redirect_to directories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directory
      @directory = Directory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directory_params
      params.require(:directory).permit(:full_path)
    end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def update
    @rating = Rating.find(rating_params[:id])
    @rating.update_attributes(score: rating_params[:score])
    render nothing: true
  end

  private
  def rating_params
    params.permit(:id, :score)
  end
end

app/helpers/directories_helper.rb
module DirectoriesHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album, html: { role: 'form' }) do |f| %>

  <legend><%= @album.name %></legend>

  <% if @album.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
      </button>

      <%= pluralize(@album.errors.count, "error") %>
      prohibited this album from being saved:
      <strong>
      <%= @album.errors.full_messages.join(", ") %>
      </strong>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :released %><br>
    <%= f.date_select :released, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :artist_id %><br>
    <%= f.text_field :artist_id, class: 'form-control' %>
  </div>
  <div class="actions form-group">
    <%= f.submit 'Submit', class: 'btn btn-success' %>
  </div>

<% end %>

app/views/albums/edit.html.erb
<h2>Edit Album</h2>

<div class="row">
  <div class="col-md-6">
    <div class="well">
      <%= render 'form' %>
    </div>
  </div>
</div>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th></th>
      <th>Artist</th>
      <th>Album</th>
      <th>Release date</th>
    </tr>
  </thead>

  <tbody>
    <% @albums.sort_by {|a| a.artist.name }.each do |album| %>
      <tr class="album" id="<%= album.id %>">
        <td><img src="<%= album.image %>"></td>
        <td><%= album.artist.name %></td>
        <td><%= album.name %></td>
        <td><%= album.released %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Album', new_album_path %>

app/views/albums/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Artist:</strong>
  <%= @album.artist.name %>
</p>

<p>
  <strong>Album:</strong>
  <%= @album.name %>
</p>

<p>
  <strong>Release date:</strong>
  <%= @album.released %>
</p>

<p>
  <img src="<%= @album.image %>">
</p>

<table class="table table-hover">
  <tr>
    <th>Track Number</th>
    <th>Track Name</th>
    <th>Duration</th>
    <th>Rating</th>
  </tr>

  <% @album.tracks.each do |t| %>
    <tr>
      <td><%= t.number %></td>
      <td><%= t.name %></td>
      <td><%= "#{t.duration / 60}:%02d" % (t.duration % 60) %></td>
      <td><div class="rating" id="<%= t.ratings.first.id %>" score="<%= t.ratings.first.score %>"></div></td>
    </tr>
  <% end %>
</table>


<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>

app/views/directories/_form.html.erb
<%= form_for(@directory) do |f| %>
  <% if @directory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@directory.errors.count, "error") %> prohibited this directory from being saved:</h2>

      <ul>
      <% @directory.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_path %><br>
    <%= f.text_field :full_path %>
  </div>
  <div class="actions">
    <%= f.submit 'Submit' %>
  </div>
<% end %>

app/views/directories/edit.html.erb
<h1>Editing directory</h1>

<%= render 'form' %>

<%= link_to 'Show', @directory %> |
<%= link_to 'Back', directories_path %>

app/views/directories/index.html.erb
<h1>Listing directories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @directories.each do |directory| %>
      <tr>
        <td><%= directory.name %></td>
        <td><%= link_to 'Show', directory %></td>
        <td><%= link_to 'Edit', edit_directory_path(directory) %></td>
        <td><%= link_to 'Destroy', directory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Directory', new_directory_path %>

app/views/directories/new.html.erb
<h1>New directory</h1>

<%= render 'form' %>

<%= link_to 'Back', directories_path %>

app/views/directories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @directory.name %>
  <%= @directory.files %>
</p>

<%= link_to 'Edit', edit_directory_path(@directory) %> |
<%= link_to 'Back', directories_path %>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">SongRank</a>
    </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", albums_path %></li>
        <li><a href="#">About</a></li>
        </li>
      </ul>

      <form class="navbar-form navbar-right">
        <input type="text" class="form-control col-lg-8" placeholder="Search">
      </form>

    </div>
  </div><!-- /.container -->
</div><!-- /.navbar -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SongRank</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<div class="container">
  <%= yield %>
</div>

</body>
</html>